[workspace]
resolver = "3"
members = ["aoc", "d01", "d02", "d03", "d04", "d05", "d06", "d07", "d08", "d09", "d10", "d11", "d12"]

[workspace.dependencies]
rayon = "1.11.0"

[profile.dev.package."*"]
opt-level = 3
